// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalDMPlace.Models;

#nullable disable

namespace PortalDMPlace.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260103214047_SettingsTableUpdate")]
    partial class SettingsTableUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PortalDMPlace.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PortalDMPlace.Models.Campanha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSimples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campanhas");
                });

            modelBuilder.Entity("PortalDMPlace.Models.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("PortalDMPlace.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChamadaCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordWebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExibirRelogioSessao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FonteFamilia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoundryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemaCorPrimaria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemaCorSecundaria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PortalDMPlace.Models.Noticia", b =>
                {
                    b.HasOne("PortalDMPlace.Models.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("PortalDMPlace.Models.Settings", b =>
                {
                    b.HasOne("PortalDMPlace.Models.Campanha", null)
                        .WithOne("Settings")
                        .HasForeignKey("PortalDMPlace.Models.Settings", "CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalDMPlace.Models.Campanha", b =>
                {
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
